### ISSUE TITLE
Local network DNS resolution doesn't work

### ISSUE THREAD

**Issue by ryfow** [concourse/concourse-lite#1]
[line 8 in update-resolv.conf.sh](https://github.com/concourse/concourse-lite/blob/master/scripts/update-resolv.conf.sh#L5) puts 8.8.8.8 into /etc/resolvconf/resolv.conf.d/head.

For me, this screws up local dns resolution, making it difficult to work with git & maven repositories on my network.

**Comment by ilackarms** [comment]
is any work being done on this issue? This is a major problem for my local team, where we are doing local development behind a corporate firewall and need to be able to configure our own DNS address for the concourse server

**Comment by xoebus** [comment]
Since we pre-build the boxes this isn't easy to change after the fact. We may be able to find a way for Vagrant to template this at VM boot?

For now, log into the machine and edit `/etc/resolv.conf` or similar file and then run `resolvconf -u`.

**Comment by chendrix** [comment]
Moved to concourse/concourse#1146
