### ISSUE TITLE
Make IP address parametizable

### ISSUE THREAD

**Issue by scottschulthess** [concourse/concourse-lite#16]
There are scenarios were you need/have to change the port this vm is on because of conflicts and whatnot, and you can change it using vagrant but then there are static references to the IP in the repo that causes certain things to break https://github.com/concourse/concourse-lite/search?utf8=%E2%9C%93&q=100

**Comment by vito** [comment]
There was a PR for this but it broke things, so we had to revert it: https://github.com/concourse/concourse-lite/pull/13

**Comment by chendrix** [comment]
Moved to concourse/concourse#1144
