### ISSUE TITLE
Cannot get the vagrant box up

### ISSUE THREAD

**Issue by meekrosoft** [concourse/concourse-lite#17]
Hi,

I'm trying out concourse and I can't seem to get the VM up and running.  Is this a known issue or a problem with my local vagrant setup?

````
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
````

Regards,
Mike

**Comment by vito** [comment]
Make sure you're on the latest VirtualBox?

**Comment by krishicks** [comment]
I have the same issue. Platform is Ubuntu 16.04.1. Updated Virtualbox and Vagrant to latest:

```
$ vboxmanage -v
5.1.12r112440
$ vagrant -v
Vagrant 1.9.1
```

Downgrading concourse/lite to 2.4.0 (chosen at random) works.

```
$ rm Vagrantfile
$ vagrant init concourse/lite --box-version 2.4.0
$ vagrant up
```

**Comment by DanielJonesEB** [comment]
@meekrosoft @krishicks Double-check that the cable is connected in `Network > Adapter > Advanced`. This stumped me for about 40 minutes the first time it happened, after which there was much facepalm.

**Comment by edysli** [comment]
Thanks @DanielJonesEB ! That was it.
Virtual cables being unplugged, oh my! I thought virtual machines would free us of cables... ;) Is there a way to fix the VM build to have that virtual cable plugged in by default in Virtualbox?

**Comment by krishicks** [comment]
After downgrading to 2.4.0 and doing nothing else I went back to the latest version and it worked.

🤷‍♂️

**Comment by chendrix** [comment]
Hi there, I'm going to close this as it looks like your question was resolved. Feel free to reopen or to ask on [slack](https://slack.concourse.ci) or on [stackoverflow](http://stackoverflow.com/questions/tagged/concourse%3E)

**Comment by edysli** [comment]
@chendrix Is there a way to fix this in the box you distribute or does this only appear on the machine running Vagrant?

**Comment by chendrix** [comment]
@edysli It's only a problem on the machine running vagrant.
