### ISSUE TITLE
image_resource is not optional

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse-lite#18]
The docs say [image_resource](http://concourse.ci/running-tasks.html#image_resource) is optional, but in concourse/lite it is not optional.

Failing to specify `image_resource` (I haven't tried `image`) results in the following error when the task runs:

```
volume graph is disabled
```

**Comment by chendrix** [comment]
It's only *Optional* in the sense that **either** image_resource or image is required. Poor documentation, but closing this here.
