### ISSUE TITLE
RFC: Merge packer templates

### ISSUE THREAD

**Issue by rickard-von-essen** [concourse/concourse-lite#5]
I was looking through the packer templates to build a Vagrant box for _Parallels Desktop for Mac_ and I found that boxes for _VMware_ and _VirtualBox_ are built from two different templates. I think they should use the same template to decrease duplication and minimise drift between the two versions.

Would you be interested in a PR where I merged the two?

**Comment by vito** [comment]
Sounds reasonable, if you're interested. We don't really maintain the VMware setup so there's no much interest from our end. Given how long we took to reply, if you want to just close this that's fine too.

**Comment by vito** [comment]
Closing this out; if you get time for a PR we'd be happy to merge it in!
